<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Общие настройки для DAL-слоя проектов DDD.</Description>
    <RootNamespace>PostSys.Dal.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Microsoft.Build.CopyOnWrite">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
  </ItemGroup>

</Project>
