<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Клиент PostSys.</Description>
    <RootNamespace>PostSys.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL.Client" />
    <PackageReference Include="GraphQL.Client.Serializer.SystemTextJson" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Build.CopyOnWrite">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\postSys.readModels.prj\postSys.readModels.csproj" />
  </ItemGroup>

</Project>
