<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
          <!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <TieredPGO>true</TieredPGO>
    <RootNamespace>PostSys.Gui</RootNamespace>
    <ApplicationIcon>..\common\postSys.gui.common.prj\Assets\logo.ico</ApplicationIcon>
    <AvaloniaUseBindingsByDefault>true</AvaloniaUseBindingsByDefault>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Buttons\info.png" />
    <None Remove="Assets\Buttons\map.png" />
    <None Remove="Assets\Buttons\package.png" />
    <None Remove="Assets\Buttons\profile.png" />
    <None Remove="Assets\Buttons\settings.png" />
    <None Remove="Assets\main_logo.png" />
    <None Remove="Assets\map.png" />
    <None Remove="Assets\package.png" />
    <None Remove="Assets\Packages\box.png" />
    <None Remove="Assets\Packages\envelope.png" />
    <None Remove="Assets\profile.png" />
  </ItemGroup>

  <ItemGroup>
    <!--This helps with theme dll-s trimming.
    If you will publish your application in self-contained mode with p:PublishTrimmed=true and it will use Fluent theme Default theme will be trimmed from the output and vice versa.
    https://github.com/AvaloniaUI/Avalonia/issues/5593 -->
    <TrimmableAssembly Include="Avalonia.Themes.Fluent" />
    <TrimmableAssembly Include="Avalonia.Themes.Default" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="Avalonia.Diagnostics" />
    <PackageReference Include="FluentIcons.Avalonia" />
    <PackageReference Include="Microsoft.Build.CopyOnWrite">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Splat.NLog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\common\postSys.framework.common.prj\postSys.framework.common.csproj" />
    <ProjectReference Include="..\common\postSys.gui.common.prj\postSys.gui.common.csproj" />
    <ProjectReference Include="..\postSys.client.prj\postSys.client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\Buttons\info.png" />
    <AvaloniaResource Include="Assets\Buttons\map.png" />
    <AvaloniaResource Include="Assets\Buttons\package.png" />
    <AvaloniaResource Include="Assets\Buttons\profile.png" />
    <AvaloniaResource Include="Assets\Buttons\settings.png" />
    <AvaloniaResource Include="Assets\main_logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\Packages\box.png" />
    <AvaloniaResource Include="Assets\Packages\envelope.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Controls\ButtonsView.axaml.cs">
      <DependentUpon>ButtonsView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
