// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostSys.Dal.Persistence;

#nullable disable

namespace PostSys.Dal.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250107125543_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostSys.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("PostSys.Domain.Packages.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PackageClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_client_id");

                    b.Property<Guid>("PackagePostmanId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_postman_id");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("PackageClientId")
                        .HasDatabaseName("ix_packages_package_client_id");

                    b.HasIndex("PackagePostmanId")
                        .HasDatabaseName("ix_packages_package_postman_id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("PostSys.Domain.Postmen.Postman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("postman_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PostmanPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("postman_package_id");

                    b.HasKey("Id")
                        .HasName("pk_postmen");

                    b.ToTable("postmen", (string)null);
                });

            modelBuilder.Entity("PostSys.Domain.Clients.Client", b =>
                {
                    b.OwnsOne("PostSys.Domain.ValueObjects.Fullname", "Fullname", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid")
                                .HasColumnName("client_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("client_name");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("text")
                                .HasColumnName("client_patronymic");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("client_surname");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId")
                                .HasConstraintName("fk_clients_clients_client_id");
                        });

                    b.OwnsOne("PostSys.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid")
                                .HasColumnName("client_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("client_phone_number");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId")
                                .HasConstraintName("fk_clients_clients_client_id");
                        });

                    b.Navigation("Fullname")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("PostSys.Domain.Packages.Package", b =>
                {
                    b.HasOne("PostSys.Domain.Clients.Client", "Client")
                        .WithMany("Packages")
                        .HasForeignKey("PackageClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_packages_clients_package_client_id");

                    b.HasOne("PostSys.Domain.Postmen.Postman", "Postman")
                        .WithMany("Packages")
                        .HasForeignKey("PackagePostmanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_packages_postman_package_postman_id");

                    b.OwnsOne("PostSys.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uuid")
                                .HasColumnName("package_id");

                            b1.Property<int>("Latitude")
                                .HasColumnType("integer")
                                .HasColumnName("package_latitude");

                            b1.Property<int>("Longitude")
                                .HasColumnType("integer")
                                .HasColumnName("package_longitude");

                            b1.HasKey("PackageId");

                            b1.ToTable("packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId")
                                .HasConstraintName("fk_packages_packages_package_id");
                        });

                    b.OwnsOne("PostSys.Domain.ValueObjects.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uuid")
                                .HasColumnName("package_id");

                            b1.Property<double>("Height")
                                .HasColumnType("double precision")
                                .HasColumnName("package_height");

                            b1.Property<double>("Length")
                                .HasColumnType("double precision")
                                .HasColumnName("package_length");

                            b1.Property<double>("Weight")
                                .HasColumnType("double precision")
                                .HasColumnName("package_weight");

                            b1.HasKey("PackageId");

                            b1.ToTable("packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId")
                                .HasConstraintName("fk_packages_packages_package_id");
                        });

                    b.OwnsOne("PostSys.Domain.ValueObjects.PackageStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uuid")
                                .HasColumnName("package_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("package_status");

                            b1.HasKey("PackageId");

                            b1.ToTable("packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId")
                                .HasConstraintName("fk_packages_packages_package_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dimensions")
                        .IsRequired();

                    b.Navigation("Postman");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("PostSys.Domain.Postmen.Postman", b =>
                {
                    b.OwnsOne("PostSys.Domain.ValueObjects.Fullname", "Fullname", b1 =>
                        {
                            b1.Property<Guid>("PostmanId")
                                .HasColumnType("uuid")
                                .HasColumnName("postman_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postman_name");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("text")
                                .HasColumnName("postman_patronymic");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postman_surname");

                            b1.HasKey("PostmanId");

                            b1.ToTable("postmen");

                            b1.WithOwner()
                                .HasForeignKey("PostmanId")
                                .HasConstraintName("fk_postmen_postmen_postman_id");
                        });

                    b.OwnsOne("PostSys.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("PostmanId")
                                .HasColumnType("uuid")
                                .HasColumnName("postman_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postman_email");

                            b1.HasKey("PostmanId");

                            b1.ToTable("postmen");

                            b1.WithOwner()
                                .HasForeignKey("PostmanId")
                                .HasConstraintName("fk_postmen_postmen_postman_id");
                        });

                    b.OwnsOne("PostSys.Domain.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("PostmanId")
                                .HasColumnType("uuid")
                                .HasColumnName("postman_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("postman_password");

                            b1.HasKey("PostmanId");

                            b1.ToTable("postmen");

                            b1.WithOwner()
                                .HasForeignKey("PostmanId")
                                .HasConstraintName("fk_postmen_postmen_postman_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Fullname")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("PostSys.Domain.Clients.Client", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("PostSys.Domain.Postmen.Postman", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
