<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Модели для чтения сервиса PostSys.</Description>
    <RootNamespace>PostSys.ReadModels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.Abstractions" />
    <PackageReference Include="Microsoft.Build.CopyOnWrite">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\common\postSys.common.prj\postSys.common.csproj" />
  </ItemGroup>

</Project>
