name: PostSys

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Master_script: build.cmd

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: $env:Master_script
